[config.wallpaper]
# Whether to set the wallpaper or not
set = true

# The base command to run for applying the wallpaper, shouldn't have spaces in it.
command = "awww"

# The arguments that will be provided to the command.
# Keywords like {{ mode }} or anything that works inside of hooks doesn't work here.
# The last argument will be the image path.
arguments = [ "img", "--transition-type", "center" , "--transition-duration", "1.2"]

#none | simple | fade | left | right | top | bottom | wipe | wave | grow
#     | center | any | outer | random

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = "hyprctl reload"

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty-colors.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "~/.config/waybar/launch.sh"

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors.ini'
output_path = '~/.config/mako/colors.ini'
post_hook = 'makoctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
